### ISSUE TITLE
Specify utf-8 encoding in logging.FileHandler

### ISSUE THREAD

**Issue by Andrej730** [MessiDaGod/instabot-master#4]
I think during initialization of logging.FileHandler Utf-8 encoding should be specified otherwise instabot may have a problems if someone is using language with other symbols but latin. For example I run into issues since I'm using cyrillic.

What I mean is replace this line:
https://github.com/MessiDaGod/instabot-master/blob/8c543d1bc3a95bd2104aebcf27c0645b8c2159f2/instabot/api/api.py#L101

With this:
```python
fh = logging.FileHandler(filename=log_filename, encoding='utf-8')
```

**Comment by MessiDaGod** [comment]
@Andrej730
